version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
    ports:
      - "8000:8000"
    command: ["./wait-for-it.sh", "db:5432", "--", "pytest", "tests/test_db.py", "-v"]

