# xPath locators

//a[text()='Home']
//button[text()='About']
//button[text()='Contacts']
//button[text()='Guest log in']
//button[text()='Sign In']
//button[text()='Sign up']
//h1[text()='Do more!']
//p[text()='With the help of the Hillel auto project, you will have the opportunity to get hands-on experience in manual testing.']
//img[@alt='Instructions']
//p[text()='Log fuel expenses']
//p[text()='Instructions and manuals']
//p[text()='Keep track of your replacement schedule and plan your vehicle maintenance expenses in advance.']
//p[text()='Watch over 100 instructions and repair your car yourself.']
//h2[text()='Contacts']
//a[@href='https://www.facebook.com/Hillel.IT.School']
//a[@href='https://t.me/ithillel_kyiv']
//a[@href='https://www.youtube.com/user/HillelITSchool?sub_confirmation=1']
//a[@href='https://www.instagram.com/hillel_itschool/']
//a[@href='https://www.linkedin.com/school/ithillel/']
//a[@href='https://ithillel.ua']
//a[contains(@href,'mailto:developer@ithillel.ua')]
//p[text()='© 2021 Hillel IT school']
//p[contains(text(),'Hillel auto developed')]
//a[@routerlink='/' and contains(@class, 'header_logo')]
//iframe[contains(@class, 'hero-video_frame')]


# CSS locators

//app-header/header/div/div/div[@class='header_left']//a[@class='header_logo']
//nav[@class='header_nav']//a[contains(text(),'Garage')]
//nav[@class='header_nav']//a[contains(text(),'Fuel expenses')]
//nav[@class='header_nav']//a[contains(text(),'Instructions') and contains(@class,'-active')]
//button[@id='userNavDropdown']
//nav[contains(@class,'user-nav_menu')]//a[contains(text(),'Garage')]
//nav[contains(@class,'user-nav_menu')]//a[contains(text(),'Fuel expenses')]
//nav[contains(@class,'user-nav_menu')]//a[contains(text(),'Instructions') and contains(@class,'disabled')]
//nav[contains(@class,'user-nav_menu')]//button[contains(text(),'Logout')]
//div[@class='sidebar']//a[contains(text(),'Garage')]
//div[@class='sidebar']//a[contains(text(),'Fuel expenses')]
//div[@class='sidebar']//a[contains(text(),'Instructions') and contains(@class,'-active')]
//div[@class='sidebar']//a[contains(text(),'Log out')]
//h1[text()='Instructions']
//div[contains(@class,'instructions-search-controls')]//button[contains(text(),'Audi')]
//div[contains(@class,'instructions-search-controls')]//button[contains(text(),'TT')]
//div[contains(@class,'instructions-search-controls')]//button[contains(text(),'Search')]
//ul[contains(@class,'instructions_list')]//li[1]//a[contains(@class,'instruction-link')]
//ul[contains(@class,'instructions_list')]//li[1]//a[contains(@class,'instruction-link')]//p[contains(@class,'instruction-link_description')]
//ul[contains(@class,'instructions_list')]//li[1]//a[contains(@class,'instruction-link')]//a[contains(@class,'instruction-link_download')]
//svg[@width='36' and @height='48']
//app-root//app-global-layout//app-header//header[contains(@class,'header')]
//button[contains(@class,'dropdown-toggle') and contains(text(),'My profile')]
//div[contains(@class,'dropdown-menu')]//button[contains(text(),'Logout')]
//app-panel-layout//div[@class='panel-layout']//div[contains(@class,'container')]